export const Actions = {
  Login: 'login',
  Logout: 'logout',
  AttemptingLogin: 'attemptingLogin',
  AttemptingLogout: 'attemptingLogout',
  FetchingUser: 'fetchingUser',
  CloseMainMenu: 'closeMainMenu',
  OpenMainMenu: 'openMainMenu',
  FetchingCharacters: 'fetchingCharacters',
  ReceiveCharacters: 'receiveCharacters',
  StartCreatingNewCharacter: 'startCreatingNewCharacter',
  DiscardNewCharacter: 'discardNewCharacter',
  SavingNewCharacter: 'savingNewCharacter',
  NewCharacterSaved: 'newCharacterSaved',
  DeletingCharacter: 'deletingCharacter',
  CharacterDeleted: 'characterDeleted',
  FetchingDialogues: 'fetchingDialogues',
  ReceiveDialogues: 'receiveDialogues',
  NewDialogueSaved: 'newDialogueSaved',
  SavingNewDialogue: 'savingNewDialogue',
  StartCreatingNewDialogue: 'startCreatingNewDialogue',
  DiscardNewDialogue: 'discardNewDialogue',
  FetchingDialogue: 'fetchingDialogue',
  ReceiveDialogue: 'receiveDialogue'
};
